# NumPy provides an efficient way to store and manipulate multi-dimensional dense arrays in Python. 

In [5]:
import numpy as np

# Some problems. Put your answers inside the print functions

In [6]:
a = np.arange(4).reshape((2,2))
print("array a:")
print(a)

print("\nMaximum value of a:")
print(np.amax(a)) 

print("\nMinimum value of a:")
print(np.amin(a)) 

print("\nReturn an array of the max in each column of a:")
print(np.amax(a,axis = 0))
print(np.amax(a,axis = 1))

print("\nReturn an array of the min in each row of a:")
print(np.amin(a,axis = 0))
print(np.amin(a,axis = 1))

print("\nReturn a, sorted within each row:")
print(np.sort(a,axis=0))
print("\nReturn a, sorted within each column:")
print()

array a:
[[0 1]
 [2 3]]

Maximum value of a:
3

Minimum value of a:
0

Return an array of the max in each column of a:
[2 3]
[1 3]

Return an array of the min in each row of a:
[0 1]
[0 2]

Return a, sorted within each row:
[[0 1]
 [2 3]]

Return a, sorted within each column:



In [7]:
b = np.arange(40).reshape((20,2))
print("array b:")
print(b)

print("\nPrint elements of the first column of b above that column's 80th percentile:")
print() 

print("\nCovariance matrix of the columns of b:")
print()

array b:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]]

Print elements of the first column of b above that column's 80th percentile:


Covariance matrix of the columns of b:



# ALWAYS SET A SEED for reproducibility

In [8]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional arra

print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
